export type CardTemplate = {
  id: string;
  label: string;
  bg: string;
  accent: string;
  ink: string;
  motif: string;
  font: string;
};

export const templates: CardTemplate[] = [
  { id: "minimal", label: "Minimal", bg: "#ffffff", accent: "#ff4d45", ink: "#07111f", motif: "none", font: "'Segoe UI', Arial, sans-serif" },
  { id: "night", label: "Gece", bg: "#07131f", accent: "#11c5c0", ink: "#ffffff", motif: "city-lines", font: "'Segoe UI', Arial, sans-serif" },
  { id: "energy", label: "Enerjik", bg: "#ffd31a", accent: "#111827", ink: "#111827", motif: "geometric", font: "'Trebuchet MS', sans-serif" },
  { id: "classic", label: "Klasik", bg: "#fffaf0", accent: "#9b7040", ink: "#4b2d18", motif: "floral", font: "Georgia, serif" },
  { id: "kilim", label: "Kilim", bg: "#fff8e8", accent: "#a52a2a", ink: "#351a12", motif: "kilim", font: "Georgia, serif" },
  { id: "bosphorus", label: "Boğaz", bg: "#f7fbff", accent: "#0a4d91", ink: "#09335f", motif: "waves", font: "'Segoe UI', Arial, sans-serif" },
  { id: "aegean", label: "Ege", bg: "#ffffff", accent: "#1766ad", ink: "#12345a", motif: "geometric", font: "'Segoe UI', Arial, sans-serif" },
  { id: "cappadocia", label: "Kapadokya", bg: "#fff3df", accent: "#a75f31", ink: "#542d19", motif: "city-lines", font: "Georgia, serif" },
  { id: "blacksea", label: "Karadeniz", bg: "#0b3d2e", accent: "#83b79b", ink: "#ffffff", motif: "waves", font: "'Segoe UI', Arial, sans-serif" },
  { id: "mediterranean", label: "Akdeniz", bg: "#fffdf6", accent: "#f3ad22", ink: "#173b68", motif: "waves", font: "'Trebuchet MS', sans-serif" },
  { id: "retro", label: "Retro", bg: "#fff0d7", accent: "#e45b27", ink: "#38251b", motif: "geometric", font: "'Trebuchet MS', sans-serif" },
  { id: "technical", label: "Teknik", bg: "#10528b", accent: "#a7d6ff", ink: "#ffffff", motif: "geometric", font: "'Segoe UI', Arial, sans-serif" },
  { id: "teacher", label: "Öğretmen", bg: "#fffdf7", accent: "#2864ac", ink: "#193558", motif: "city-lines", font: "'Trebuchet MS', sans-serif" },
  { id: "health", label: "Sağlık", bg: "#effcfc", accent: "#159398", ink: "#13575a", motif: "waves", font: "'Segoe UI', Arial, sans-serif" },
  { id: "engineer", label: "Mühendis", bg: "#f5f6f7", accent: "#59636d", ink: "#11181f", motif: "geometric", font: "'Segoe UI', Arial, sans-serif" },
  { id: "monochrome", label: "Monokrom", bg: "#ffffff", accent: "#111111", ink: "#111111", motif: "none", font: "Arial, sans-serif" },
  { id: "pastel", label: "Pastel", bg: "#fff7f4", accent: "#8971a8", ink: "#514168", motif: "floral", font: "'Trebuchet MS', sans-serif" },
  { id: "neon", label: "Neon", bg: "#080816", accent: "#ff2bd6", ink: "#58f7ff", motif: "city-lines", font: "'Segoe UI', Arial, sans-serif" },
  { id: "nature", label: "Doğa", bg: "#fbfcef", accent: "#647e4d", ink: "#32442a", motif: "floral", font: "Georgia, serif" },
  { id: "premium", label: "Premium", bg: "#111313", accent: "#c77b39", ink: "#f2c38f", motif: "geometric", font: "Georgia, serif" },
  { id: "charcoal", label: "Charcoal Lüks", bg: "#2B2B2B", accent: "#C08A4E", ink: "#F5F0E8", motif: "none", font: "'Montserrat', sans-serif" },
  { id: "executive", label: "Executive", bg: "#0F1F3D", accent: "#C9A227", ink: "#FFFFFF", motif: "none", font: "'Playfair Display', Georgia, serif" },
  { id: "cream", label: "Krem Minimal", bg: "#F0EFED", accent: "#B9B1A6", ink: "#2B2B2B", motif: "none", font: "'Montserrat', sans-serif" },
  { id: "blueprint", label: "Blueprint", bg: "#10243E", accent: "#7FB3E8", ink: "#FFFFFF", motif: "geometric", font: "'Space Grotesk', sans-serif" },
  { id: "neomint", label: "Neo-Mint", bg: "#EAF6F0", accent: "#1FAE7A", ink: "#1B1B1B", motif: "waves", font: "'Poppins', sans-serif" },
  { id: "gothic", label: "Gotik Kontrast", bg: "#000000", accent: "#E63946", ink: "#FFFFFF", motif: "none", font: "'Bebas Neue', 'Arial Black', sans-serif" },
  { id: "pop", label: "Pop", bg: "#FFF7E6", accent: "#FF3D57", ink: "#111111", motif: "geometric", font: "'Archivo Black', 'Arial Black', sans-serif" },
  { id: "postcard", label: "Vintage Kartpostal", bg: "#F4E9D8", accent: "#C4622D", ink: "#3A2E28", motif: "floral", font: "'Fraunces', Georgia, serif" },
  { id: "saas", label: "Tech Clean", bg: "#FFFFFF", accent: "#4361EE", ink: "#1B1B1B", motif: "none", font: "'Space Grotesk', sans-serif" },
  { id: "parkalert", label: "Park Uyarı", bg: "#FFFFFF", accent: "#FF6B00", ink: "#111111", motif: "none", font: "'Poppins', sans-serif" },
  { id: "ui-glass", label: "Glassmorphism", bg: "#F4F8FF", accent: "#8F7CFF", ink: "#101828", motif: "waves", font: "'Space Grotesk', sans-serif" },
  { id: "ui-darkdev", label: "Dark Developer", bg: "#0B1020", accent: "#3B82F6", ink: "#E5E7EB", motif: "geometric", font: "'JetBrains Mono', monospace" },
  { id: "ui-command", label: "Command Palette", bg: "#0F172A", accent: "#60A5FA", ink: "#F9FAFB", motif: "none", font: "'JetBrains Mono', monospace" },
  { id: "ui-neumorph", label: "Neumorphism", bg: "#EEF2F7", accent: "#5B6B7C", ink: "#1F2937", motif: "none", font: "'Poppins', sans-serif" },
  { id: "ui-fluent", label: "Fluent 11", bg: "#F5F9FF", accent: "#2F6FEB", ink: "#111827", motif: "none", font: "'Segoe UI', sans-serif" },
  { id: "ui-terminal", label: "Terminal", bg: "#0B1220", accent: "#22C55E", ink: "#E5E7EB", motif: "none", font: "'JetBrains Mono', monospace" },
  { id: "ui-workspace", label: "Workspace", bg: "#0F172A", accent: "#6366F1", ink: "#E5E7EB", motif: "geometric", font: "'Space Grotesk', sans-serif" },
  { id: "ui-winform", label: "Windows Klasik", bg: "#D4D0C8", accent: "#000080", ink: "#000000", motif: "none", font: "'Segoe UI', Tahoma, sans-serif" },
  { id: "ui-cyberpunk", label: "Cyberpunk HUD", bg: "#020617", accent: "#22D3EE", ink: "#D1FAE5", motif: "city-lines", font: "'Space Grotesk', sans-serif" },
  { id: "ui-brutal", label: "Neo-Brutalizm", bg: "#FFFFFF", accent: "#EF4444", ink: "#000000", motif: "geometric", font: "'Archivo Black', 'Arial Black', sans-serif" },
  { id: "ui-clay", label: "Claymorphism", bg: "#FCE7F3", accent: "#EC4899", ink: "#334155", motif: "none", font: "'Poppins', sans-serif" },
  { id: "arcade", label: "8-Bit Arcade", bg: "#1A1035", accent: "#FFD400", ink: "#F1ECFF", motif: "none", font: "'Press Start 2P', monospace" },
  { id: "synthwave", label: "Synthwave", bg: "#2B0B3F", accent: "#FF2E97", ink: "#FFF0FB", motif: "none", font: "'Bebas Neue', sans-serif" },
  { id: "cassette", label: "Retro Kaset", bg: "#EDE3D1", accent: "#E4572E", ink: "#2B2118", motif: "none", font: "'Archivo Black', sans-serif" },
  { id: "comic", label: "Çizgi Roman", bg: "#FFE64D", accent: "#E63946", ink: "#111111", motif: "none", font: "'Archivo Black', sans-serif" },
  { id: "popart", label: "Pop Art", bg: "#FF4D6D", accent: "#FFE14D", ink: "#1A1A1A", motif: "none", font: "'Archivo Black', sans-serif" },
  { id: "sticker", label: "Holografik Sticker", bg: "#F7F7FB", accent: "#7C3AED", ink: "#1B1030", motif: "none", font: "'Poppins', sans-serif" },
  { id: "racing", label: "Motorsport", bg: "#0D0D0D", accent: "#E10600", ink: "#F5F5F5", motif: "none", font: "'Anton', sans-serif" },
  { id: "boarding", label: "Bilet / Boarding", bg: "#FFFFFF", accent: "#1E6FEB", ink: "#10233F", motif: "none", font: "'JetBrains Mono', monospace" },
  { id: "highway", label: "Otoyol Levhası", bg: "#0E7A3B", accent: "#FFFFFF", ink: "#FFFFFF", motif: "none", font: "'Space Grotesk', sans-serif" },
  { id: "kilimmodern", label: "Modern Kilim", bg: "#F6ECDD", accent: "#B5341F", ink: "#3A241A", motif: "kilim", font: "'Fraunces', Georgia, serif" },
  { id: "iznik", label: "İznik Çini", bg: "#F1F7FF", accent: "#1F5FB8", ink: "#123059", motif: "floral", font: "'Playfair Display', Georgia, serif" },
  { id: "sunset", label: "Gün Batımı", bg: "#2A1A3E", accent: "#FFFFFF", ink: "#FFF6EF", motif: "none", font: "'Poppins', sans-serif" },
  { id: "voxel", label: "Voxel Blok", bg: "#8BC34A", accent: "#5D4037", ink: "#1B2E0F", motif: "none", font: "'Press Start 2P', monospace" },
  { id: "galaxy", label: "Galaksi Efsanesi", bg: "#05010F", accent: "#FFE81F", ink: "#E8ECFF", motif: "none", font: "'Anton', sans-serif" },
  { id: "hero", label: "Süper Kahraman", bg: "#1565C0", accent: "#FFC107", ink: "#FFFFFF", motif: "none", font: "'Archivo Black', sans-serif" },
  { id: "manga", label: "Manga", bg: "#FFFFFF", accent: "#111111", ink: "#111111", motif: "none", font: "'Archivo Black', sans-serif" },
  { id: "pirate", label: "Korsan Haritası", bg: "#E7D3A1", accent: "#6B4226", ink: "#3A2A16", motif: "none", font: "'Fraunces', Georgia, serif" },
  { id: "matrix", label: "Kod Yağmuru", bg: "#020A02", accent: "#00FF66", ink: "#B9FFCE", motif: "none", font: "'JetBrains Mono', monospace" },
];
